In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("government-procurement.csv")

In [4]:
df.head()

,tender_no.,tender_description,agency,award_date,tender_detail_status,supplier_name,awarded_amt
0,ACR000ETT14000007,Provision Of Event Management And Related Serv...,Accounting And Corporate Regulatory Authority,06-02-2015,Awarded to No Suppliers,Unknown,0.00
1,ACR000ETT14000008,Invitation To Tender For The Provision Of Alte...,Accounting And Corporate Regulatory Authority,30-04-2015,Awarded to No Suppliers,Unknown,0.00
2,ACR000ETT14000009,Invitation To Tender For The Provision Of Manp...,Accounting And Corporate Regulatory Authority,28-01-2015,Awarded to Suppliers,RMA CONTRACTS PTE. LTD.,76071.21
3,ACR000ETT15000004,Invitation To Tender For The Provision Of Manp...,Accounting And Corporate Regulatory Authority,01-07-2015,Awarded to Suppliers,TESCOM (SINGAPORE) SOFTWARE SYSTEMS TESTING PT...,84000.00
4,ACR000ETT15000005,Proposed Interior Fitting Out Works for ACRA's...,Accounting And Corporate Regulatory Authority,24-04-2015,Awarded to Suppliers,MKS GLOBAL PTE. LTD.,653255.00

In [5]:
df.tail()

,tender_no.,tender_description,agency,award_date,tender_detail_status,supplier_name,awarded_amt
32751,WSG000ETT20300008,PROVISION OF INTEGRATED FACILITIES MANAGEMENT ...,Workforce Singapore,09-12-2020,Awarded to Suppliers,GUTHRIE FMC PTE. LTD.,4269564.0
32752,WSG000ETT20300010,INVITATION TO TENDER FOR RENEWAL OF SOFTWARE M...,Workforce Singapore,10-12-2020,Awarded to Suppliers,SQLNET PTE. LTD.,534800.0
32753,WSG000ETT20300011,SGUnited Jobs and Skills Placement Partners,Workforce Singapore,05-03-2021,Awarded to Suppliers,ADECCO PERSONNEL PTE LTD,1550.0
32754,WSG000ETT20300012,JOB EVALUATION EXERCISE AND COMPENSATION REVIEW,Workforce Singapore,05-02-2021,Awarded to Suppliers,CARROTS CONSULTING PTE LTD,70000.0
32755,WSG000ETT20300013,PROVISION OF APPLICATION MAINTENANCE (AGILE) A...,Workforce Singapore,10-02-2021,Awarded to Suppliers,PLEODATA PTE. LTD.,491049.0

In [6]:
df.shape

(32756, 7)

In [7]:
df.columns

Index(['tender_no.', 'tender_description', 'agency', 'award_date',
       'tender_detail_status', 'supplier_name', 'awarded_amt'],
      dtype='str')

In [8]:
df.dtypes

tender_no.                  str
tender_description          str
agency                      str
award_date                  str
tender_detail_status        str
supplier_name               str
awarded_amt             float64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32756 entries, 0 to 32755
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   tender_no.            32756 non-null  str
 1   tender_description    32756 non-null  str
 2   agency                32756 non-null  str
 3   award_date            32756 non-null  str
 4   tender_detail_status  32756 non-null  str
 5   supplier_name         32756 non-null  str
 6   awarded_amt           32756 non-null  float64
dtypes: float64(1), str(6)
memory usage: 1.7 MB

In [10]:
df.describe()

        awarded_amt
count  3.275600e+04
mean   3.942861e+06
std    3.415095e+07
min    0.000000e+00
25%    1.800075e+04
50%    1.649915e+05
75%    7.047750e+05
max    1.988000e+09

In [11]:
df.describe(include="all")

,tender_no.,tender_description,agency,award_date,tender_detail_status,supplier_name,awarded_amt
count,32756,32756,32756,32756,32756,32756,3.275600e+04
unique,23909,23081,122,1729,3,8633,NaN
top,FINVITETT19300003,ITT for the Provision of Singapore Hotel and S...,Housing and Development Board,12-03-2018,Awarded to Suppliers,Unknown,NaN
freq,109,109,2223,143,26257,1414,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,3.942861e+06
std,NaN,NaN,NaN,NaN,NaN,NaN,3.415095e+07
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.800075e+04
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.649915e+05
75%,NaN,NaN,NaN,NaN,NaN,NaN,7.047750e+05
max,NaN,NaN,NaN,NaN,NaN,NaN,1.988000e+09

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.nunique()

tender_no.              23909
tender_description      23081
agency                    122
award_date               1729
tender_detail_status        3
supplier_name            8633
awarded_amt             21832
dtype: int64

In [14]:
df.isnull().sum()

tender_no.              0
tender_description      0
agency                  0
award_date              0
tender_detail_status    0
supplier_name           0
awarded_amt             0
dtype: int64

In [15]:
df["award_date"] = pd.to_datetime(
    df["award_date"],
    format="%d-%m-%Y"
)

In [16]:
df["award_date"].dtype

dtype('<M8[us]')

In [17]:
df["award_year"] = df["award_date"].dt.year

In [18]:
df["award_month"] = df["award_date"].dt.month

In [19]:
df["award_month_name"] = df["award_date"].dt.month_name()

In [20]:
df["award_quarter"] = df["award_date"].dt.quarter

In [21]:
df["award_day_name"] = df["award_date"].dt.day_name()

In [22]:
df.to_csv("government_procurement_cleaned.csv", index=False)